<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Posts;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Posts::insert([
            // EPISÓDIOS
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 1: O que são malwares?',
                'caption' => 'O que são Malwares? Quais são os principais tipos? A gente fala um pouquinho disso para vocês!',
                'content' => 'O que são Malwares? Quais são os principais tipos? A gente fala um pouquinho disso para vocês!',
                'link' => 'https://open.spotify.com/episode/7CWaOxJwvMlbBNupDKF7Ub',
                'slug' => 'episodio-1-o-que-sao-malwares',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 2: Antivírus e senhas',
                'caption' => 'Qual a importância de um antivírus? Como criar uma boa senha?',
                'content' => 'Qual a importância de um antivírus? Como criar uma boa senha?',
                'link' => 'https://open.spotify.com/episode/1tGe55S7Itf8Tl575aS3TN',
                'slug' => 'episodio-2-antivirus-e-senhas',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 3: Garotas na informática',
                'caption' => 'Nesse episódio conversamos com a professora Jéssica Diniz sobre inclusão feminina na informática.',
                'content' => 'Nesse episódio conversamos com a professora Jéssica Diniz sobre inclusão feminina na informática.',
                'link' => 'https://open.spotify.com/episode/3OPnxQ1kNOEbklT8lpc6GQ',
                'slug' => 'episodio-3-garotas-na-informatica',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 4: A informática tem cor?',
                'caption' => 'Nesse episódio, falaremos sobre a questão racial no meio tecnológico com os convidados prof. Igor Gacheiro, prof. Eduardo Henrique e a aluna Lívia Alves.',
                'content' => 'Nesse episódio, falaremos sobre a questão racial no meio tecnológico com os convidados prof. Igor Gacheiro, prof. Eduardo Henrique e a aluna Lívia Alves.',
                'link' => 'https://open.spotify.com/episode/6N2vzaWV1MbZFmtAVWNgxE',
                'slug' => 'episodio-4-a-informatica-tem-cor',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 5: Como as empresas ganham dinheiro com as nossas informações?',
                'caption' => 'O nosso quinto episódio traz a resposta para a seguinte pergunta: como empresas, por exemplo o Facebook, ganham dinheiro com nossos dados?',
                'content' => 'O nosso quinto episódio traz a resposta para a seguinte pergunta: como empresas, por exemplo o Facebook, ganham dinheiro com nossos dados?',
                'link' => 'https://open.spotify.com/episode/4G0RjqxyPGArM7NnkQ8YI8',
                'slug' => 'episodio-5-como-as-empresas-ganham-dinheiro-com-as-nossas-informacoes',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 6: 5G e a disputa EUA x China',
                'caption' => 'No 06 episódio temos uma discussão sobre um assunto que vai determinar o futuro das comunicações: o 5G!',
                'content' => 'No 06 episódio temos uma discussão sobre um assunto que vai determinar o futuro das comunicações: o 5G!',
                'link' => 'https://open.spotify.com/episode/4A0Kw5S84kmRD3scqiPcfk',
                'slug' => 'episodio-6-5g-e-a-disputa-eua-x-china',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 7: Os riscos da superexposição nas redes sociais',
                'caption' => 'No nosso sétimo episodio falaremos sobre os riscos da superexposição nas redes sociais para os usuários e como podemos mudar nosso mau uso.',
                'content' => 'No nosso sétimo episodio falaremos sobre os riscos da superexposição nas redes sociais para os usuários e como podemos mudar nosso mau uso.',
                'link' => 'https://open.spotify.com/episode/3nxQ31uFzwJQZaFPjEkOki',
                'slug' => 'episodio-7-os-riscos-da-superexposicao-nas-redes-sociais',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [   
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 8: O uso excessivo das redes sociais e a manipulação do algoritmo',
                'caption' => 'Aqui você vai ficar por dentro de como o algoritmo pode te manipular a ponto de você se sentir dependente do seu celular e as redes sociais',
                'content' => 'Aqui você vai ficar por dentro de como o algoritmo pode te manipular a ponto de você se sentir dependente do seu celular e as redes sociais',
                'link' => 'https://open.spotify.com/episode/61dVI63VLtO53WPwJ8Zky5',
                'slug' => 'episodio-8-o-uso-excessivo-das-redes-sociais-e-a-manipulacao-do-algoritmo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'e',
                'title' => 'Episódio 9: Saúde mental nas redes sociais', 'Os impactos das redes sociais na nossa saúde: prejuízos, consequências e formas de prevenção',
                'caption' => 'Os impactos das redes sociais na nossa saúde: prejuízos, consequências e formas de prevenção',
                'content' => 'Os impactos das redes sociais na nossa saúde: prejuízos, consequências e formas de prevenção',
                'link' => 'episodio-9-saude-mental-nas-redes-sociais',
                'slug' => 'episodio-8-o-uso-excessivo-das-redes-sociais-e-a-manipulacao-do-algoritmo',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // NOTÍCIAS
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'n',
                'title' => 'Lançamento do Python 3.13: O que Esperar',
                'caption' => 'Novas funcionalidades e melhorias na próxima versão do Python.',
                'content' => 'O Python 3.13 está programado para ser lançado em outubro de 2024, trazendo melhorias no suporte, extensões de segurança, e uma série de mudanças importantes na biblioteca padrão.',
                'link' => 'https://realpython.com/python-news-may-2024/',
                'slug' => 'lancamento-do-python-313-o-que-esperar',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'n',
                'title' => 'Mercado de Programação em Alta: Oportunidades e Desafios',
                'caption' => 'O crescimento acelerado da demanda por desenvolvedores no Brasil.',
                'content' => 'Com o aumento da digitalização das empresas, a procura por profissionais de programação está em alta.',
                'link' => 'https://www.folha.uol.com.br/',
                'slug' => 'mercado-de-programacao-em-alta-oportunidades-e-desafios',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'n',
                'title' => 'JavaScript em 2024: Tendências e Futuro',
                'caption' => 'Discussões sobre o futuro do JavaScript e seu papel na evolução do desenvolvimento web.',
                'content' => 'Novos frameworks e bibliotecas continuam emergindo, mas a base sólida do JavaScript ainda domina o mercado.',
                'link' => 'https://javascript.info/',
                'slug' => 'javascript-em-2024-tendencias-e-futuro',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ARTIGOS
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'a',
                'title' => 'Dicas para Gerenciar Projetos de Software',
                'caption' => 'Técnicas ágeis e melhores práticas para gerenciar projetos complexos.',
                'content' => 'Gerenciar um projeto de software exige planejamento detalhado, comunicação clara e uso eficiente de ferramentas de colaboração.',
                'link' => 'https://projectmanagement.com/',
                'slug' => 'dicas-para-gerenciar-projetos-de-software',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'a',
                'title' => 'Por que Escolher o Laravel para seu Projeto?',
                'caption' => 'Vantagens do framework Laravel no desenvolvimento web moderno.',
                'content' => 'O Laravel é uma das ferramentas mais completas e utilizadas no mercado por sua robustez e simplicidade.',
                'link' => 'https://laravel.com/',
                'slug' => 'por-que-escolher-o-laravel-para-seu-projeto',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'users_id' => 1,
                'author' => 'Gabriel Mendes',
                'type' => 'a',
                'title' => 'Segurança Digital: Como Proteger seus Dados',
                'caption' => 'Estratégias e dicas práticas para proteger seus dados na internet.',
                'content' => 'A segurança digital é uma preocupação crescente. Aprenda como criar senhas fortes, usar VPNs e reconhecer possíveis ameaças.',
                'link' => 'https://cybersecurity.com/',
                'slug' => 'seguranca-digital-como-proteger-seus-dados',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
